# coding=utf-8
"""配置flash抛出的提示信息"""
PROFILE_UPDATE = u"个人资料已更新"
INVALID_USER = u"未找到此人"
INVALID_TOPIC = u"未找到此话题"
CANNOT_CON_MYSELF = u"不能关注自己"
ALREADY_CON = u'已经关注'
NO_CON = u'未关注此人'
AVATAR_MODI_FAIL = u"头像修改失败"
WRONG = u"错误的用户名或密码"
WRONG_PWD = u"密码错误"
SEND_EMIAL = u"验证邮件已发送到你的邮箱，请先登录"
VERIFI_SUCCESS = u"账户验证成功"
LINK_FAIL = u"验证链接已过期或无效."
EMAIL_UPDATE = u"邮箱账户已修改"
UPDATE_FAIL = u"未修改成功"
UPDATE_SUCC = u"更新成功"
QUESTION_ERROR = u"问题或问题描述过长"
COMMENT_ERROR = u"评论过长"
FAIL = u"操作失败"
NOFOUND=u'未找到'
